name: Lint and build

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint and build
        uses: ./.github/actions/lint-and-build
        with:
          node-version: '20.13.1'
